from tkinter import *
def name():
    print(z.get())
    print(z1.get())
    print(z2.get())
    print(z3.get())
    print(z4.get())
    print(z5.get())
w=Tk()
w.geometry("500x500")
w.title("SCHOOL LIBRARY")
w.resizable(0,0)
Label(w,text="FIRST NAME:").grid(row=1,column=1)
Label(w,text="LAST NAME:").grid(row=2,column=1)
Label(w,text="ROLL NO:").grid(row=3,column=1)
Label(w,text="PHONE NO:").grid(row=4,column=1)
Label(w,text="ADDRESS:").grid(row=5,column=1)
Label(w,text="EMAIL ID NO:").grid(row=6,column=1)
Label(w,text="PASSWORD:").grid(row=7,column=1)
Label(w,text="LANGUAGE:").grid(row=8,column=1)
Checkbutton(w,text="ENGLISH").grid(row=8,column=2)
Checkbutton(w,text="MARATHI").grid(row=9,column=2)
Checkbutton(w,text="HINDI").grid(row=10,column=2)
Label(w,text="GENDER").grid(row=11,column=1)
Radiobutton(w,text="MALE",value=0).grid(row=11,column=2)
Radiobutton(w,text="FEMALE",value=1).grid(row=11,column=3)
z=Entry(w)
z.grid(row=1,column=2)
z1=Entry(w)
z1.grid(row=2,column=2)
z2=Entry(w)
z2.grid(row=3,column=2)
z3=Entry(w)
z3.grid(row=4,column=2)
z4=Entry(w)
z4.grid(row=5,column=2)
z5=Entry(w)
z5.grid(row=6,column=2)
Entry(w,show="*").grid(row=7,column=2)
btn=Button(w,text="SUBMIT", command=name)
btn.grid(row=15,column=12)
