from tkinter import *
from tkinter import messagebox
import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="password123",database="library")
def db():
    mycursor=mydb.cursor()
    mycursor.execute("insert into schoollibrary values('{}','{}',{},{},'{}','{}','{}','{}')".format(z.get(),z1.get(),z2.get(),z3.get(),z4.get(),z5.get(),z6.get(),z7.get(),z8.get(),z9.get()))
    mydb.commit()
    messagebox.showinfo("Hello","Submission Successful")
    mydb.close()
    for i in mycursor:
        print(i)
def name():
    print(z.get())
    print(z1.get())
    print(z2.get())
    print(z3.get())
    print(z4.get())
    print(z5.get())
    print(z6.get())
    print(z7.get())
    print(z8.get())
w=Tk()
w.geometry("500x500")
w.title("SCHOOL LIBRARY")
w.resizable(0,0)
c1=StringVar()
c2=StringVar()
c3=StringVar()
r1=StringVar()
r2=StringVar()
Label(w,text="FIRST NAME:").grid(row=1,column=1)
Label(w,text="LAST NAME:").grid(row=2,column=1)
Label(w,text="ROLL NO:").grid(row=3,column=1)
Label(w,text="PHONE NO:").grid(row=4,column=1)
Label(w,text="ADDRESS:").grid(row=5,column=1)
Label(w,text="EMAIL ID:").grid(row=6,column=1)
Label(w,text="PASSWORD:").grid(row=7,column=1)
Label(w,text="LANGUAGE:").grid(row=8,column=1)
Checkbutton(w,text="ENGLISH",variable=c1,onvalue="English").grid(row=9,column=2)
Checkbutton(w,text="MARATHI",variable=c2,onvalue="Marathi").grid(row=10,column=2)
Checkbutton(w,text="HINDI",variable=c3,onvalue="Hindi").grid(row=11,column=2)
Label(w,text="GENDER:").grid(row=12,column=1)
Radiobutton(w,text="MALE",variable=r1,value="male").grid(row=12,column=2)
Radiobutton(w,text="FEMALE",variable=r2,value="female").grid(row=12,column=3)    
z=Entry(w)
z.grid(row=1,column=2)
z1=Entry(w)
z1.grid(row=2,column=2)
z2=Entry(w)
z2.grid(row=3,column=2)
z3=Entry(w)
z3.grid(row=4,column=2)
z4=Entry(w)
z4.grid(row=5,column=2)
z5=Entry(w)
z5.grid(row=6,column=2)
z6=Entry(w)
z6.grid(row=7,column=2)
z7=Entry(w)
z7.grid(row=8,column=2)
z8=Entry(w)
z8.grid(row=8,column=2)
z9=Entry(w)
z9.grid(row=10,column=2)
Entry(w,show="*").grid(row=7,column=2)
btn=Button(w,text="SUBMIT",command=db)
btn.grid(row=15,column=12)


